# Generated by Django 6.0.1 on 2026-01-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="brightness",
            field=models.CharField(
                blank=True,
                choices=[("light", "Light"), ("medium", "Medium"), ("dark", "Dark")],
                max_length=10,
                null=True,
            ),
        ),
    ]
