# Generated by Django 6.0.1 on 2026-01-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_productvariant_brightness"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productvariant",
            name="sku",
        ),
        migrations.AddField(
            model_name="product",
            name="sku",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
