# Generated by Django 6.0.1 on 2026-01-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_remove_productvariant_sku_product_sku_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_text", models.CharField(max_length=255, unique=True)),
                (
                    "category_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("result_data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "count",
                    models.PositiveIntegerField(
                        default=1, help_text="How many times this query was made"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Search Queries",
            },
        ),
    ]
