from django.db import models
from django.utils.text import slugify

class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name

class Product(models.Model):
    # --- Basic Info ---
    # Many-to-Many: A product can belong to multiple categories (e.g., "Men", "Sale")
    categories = models.ManyToManyField(Category, related_name='products')
    name = models.CharField(max_length=200)
    sku = models.CharField(max_length=100, blank=True, null=True)
    slug = models.SlugField(unique=True, blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    
    # --- AI Section ---
    # Detailed description generated by Vertex AI
    ai_description = models.TextField(blank=True, verbose_name="AI Description")
    # Keywords detected by AI (saved as a list: ["cotton", "summer"])
    ai_tags = models.JSONField(default=list, blank=True, verbose_name="AI Tags")
    # Vector embedding for semantic search (saved as a list of floats for now)
    ai_embedding = models.JSONField(default=list, blank=True, verbose_name="AI Embedding")
    
    # Structured features generated by AI (e.g., style, pattern, material)
    features = models.JSONField(default=dict, blank=True, verbose_name="AI Features")

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            if self.sku:
                self.slug = slugify(f"{self.name}-{self.sku}")
            else:
                self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

class ProductVariant(models.Model):
    """
    Physical items in stock, representing a specific combination of product, color, size, and brightness.
    """
    BRIGHTNESS_CHOICES = [
        ('light', 'Light'),
        ('medium', 'Medium'),
        ('dark', 'Dark'),
    ]
    product = models.ForeignKey(Product, related_name='variants', on_delete=models.CASCADE)
    size = models.CharField(max_length=50)
    color = models.CharField(max_length=50)
    brightness = models.CharField(max_length=10, choices=BRIGHTNESS_CHOICES, blank=True, null=True)
    stock_quantity = models.PositiveIntegerField(default=0)
    
    class Meta:
        unique_together = ('product', 'size', 'color', 'brightness')
        verbose_name_plural = "Product Variants"

    def __str__(self):
        return f"{self.product.name} - {self.color} ({self.brightness}) - {self.size}"

class SearchQuery(models.Model):
    query_text = models.CharField(max_length=255, unique=True)
    category_name = models.CharField(max_length=100, blank=True, null=True)
    # Store the extracted filter data (colors, filters, suggestions) as JSON
    result_data = models.JSONField()
    
    created_at = models.DateTimeField(auto_now_add=True)
    count = models.PositiveIntegerField(default=1, help_text="How many times this query was made")

    class Meta:
        verbose_name_plural = "Search Queries"

    def __str__(self):
        return self.query_text

class ProductImage(models.Model):
    """
    An image for a specific ProductVariant.
    """
    variant = models.ForeignKey(ProductVariant, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products/')
    is_main = models.BooleanField(default=False, help_text="Is this the main image displayed for the variant?")

    def __str__(self):
        return f"Image for {self.variant}"